### ISSUE TITLE
Accessibility Audit of the Website

### ISSUE THREAD

**Issue by aaa12345678910** [codeforsanjose/gov-agenda-notifier#20] opened 2020-10-07 02:22 UTC
Accessibility Audit of the Website

- [ ] Fix issues found on Lighthouse Report conducted October 23, 2020:

![Screen Shot 2020-10-23 at 10 57 24 AM](https://user-images.githubusercontent.com/20962963/97037864-c435e280-151e-11eb-92f0-825a6095e566.png)

TODO: 

- [ ] Conduct a more indepth a11y audit

https://developers.google.com/web/fundamentals/accessibility/how-to-review?utm_source=lighthouse&utm_medium=devtools

**Comment by jeffersonken19** [comment] 2021-01-13 01:51
Duplicate of: https://github.com/codeforsanjose/gov-agenda-notifier/issues/50

**Closed by jeffersonken19** 2021-01-13 01:52 UTC
